jokes = ["Co to jest? Leży na trawie i nie dycha? Dwie dychy.",
         "Co nasz prezydent wpisuje w rubrykę ''zawód''? Chlebowski",
         "Dlaczego chińczycy nie mogą się włamać na serwery? Każdy z nich próbował wpisać hasło",
         "Co korniki mają na obiad? Stół szwedzki",
         "Co robi atakowany kucharz? Wzywa posiłki",
         "Czym stuka chleb w piekarniku? Piętką",
         "Jaka jest ulubiona bajka ''dresów''? Brzydkie karczątko",
         "Kto to jest hipochondryk? To ktoś, co czuje się lepiej,gdy czuje się gorzej",
         "Po czym poznać, że mężczyzna się zakochał? Przez kilka dni nie interesuje się swoim samochodem",
         "Co jest wielkie, szare i brzmi podobnie jak słowik? Słonik",
         "Dlaczego faceci nie maja celluitu? Bo to nieładne jest",
         "Dlaczego dziecko ciągle krzyczy? Czego ono chce?Ono Chce Krzyczeć",
         "Jak się nazywa najpopularniejsza broń piracka? Kopia",
         "Jaka jest różnica między walcem angielskim a wiedeńskim? Wiedeński jeździ lewą stroną",
         "Co jest piękniejszego niż piękna kobieta? Raczej nic,ale piękne akwarium jest tańsze w utrzymaniu",
         "Dlaczego zespoły metalowe szybko grają? Bo gry człowiek się spieszy, to diabeł się cieszy",
         "Jak rosyjskie koty rozliczają się za gościnę ze swoimi właścicielami? Wrublach",
         "Czy pływanie wyszczupla? Jeśli tak, to co wieloryby robią źle.",
         "Jaki jest szczyt skąpstwa? Puścić komuś sygnał przez skype",
         "Kto robi modele żaglowców w butelkach? Emerytowani ginegolodzy",
         "Jak się nazywa interaktywna telewizja dla kotów? Akwarium",
         "Co to jest prawdomówność? Brak umiejętności, wymyślenia innego wariantu",
         "Dlaczego mrówki nie chodzą do kościoła? Bo to insekty",
         "Co łączy ojca z kaloryferem? Oboje muszą być twardzi i ciepli",
         "Gdzie można znaleźć psa bez przednich lub tylnych łap? Tam gdzie się go zostawiło",
         "Myli się tylko raz? Brudasy",
         "Co jest przyczyna rozwodów? Małżeństwa",
         "Jak poprawnie politycznie powiedzieć 'tłuścioch'? Nadwagoamerykanin",
         "Co ma na głowie renifer z niedoborem wapnia w kościach? Oseoporoże",
         "Co zrobił Kopernik? Zatrzymał wakacje, poruszył turystów.",
         "Dlaczego Polska nie słynie z dobrych bramkarzy? Bo słynie z dobrych dyskotek.",
         "Co Niemcy myślą o Tomaszu Majewskim? Ładna z niego laska",
         "Gdzie jest najwięcej witamin? W aptece",
         "Jak wygląda Gęś ? Gęś wygląda oczami.",
         "Mamo, mam już 15 lat. Mogę zacząć nosić stanik ? Nie zawracaj mi głowy, Andrzejku.",
         "Ile zwierząt wziął na Arkę Mojżesz ? Zero, Mojżesz nie miał Arki.",
         "Jaka jest różnica między komputerem a praniem ? Inaczej się zawiesza.",
         "Dlaczego Batman miał 5 z wf-u ? Bo zawsze miał strój.",
         "Najlepsze ciasto szefa? Tyraj-misiu",
         "Facet słyszy strzały w szafie, otwiera - a tam marynarka wojenna",
         "Kto obejrzał wszystkie odcinki 'Mody na sukces'? Lektor",
         "Jak pokonać człowieka-pająka? Człowiekiem-kapciem.",
         "Co ja na kolację Miś Uszatek? Pora na dobranoc.",
         "Jak stracić na wadzę? Kupić za 100, a sprzedać za 50",
         "Jak się nazywa bumerang który nie wraca? Patyk.",
         "Kiedy krzesło ma depresje? Kiedy nie ma oparcia.",
         "Co robią transformersy po wyjściu z imprezki? Składają się na taksówkę.",
         "Jakie jest lekarstwo na miłość od pierwszego wejrzenia? Spojrzeć drugi raz.",
         "Jak powstają pioruny? Błyskawicznie.",
         "Co ma 10.000 kalorii? 5.000 tik-taków.",
         "Czemu niedźwiedź chodzi w futrze? Bo jakby wyglądał w płaszczu przeciwdeszczowym...",
         "Dlaczego orkiestra nie gra na moście? Bo most to nie instrument",
         "Jaka jest różnica między punktem G, a pubem? Wielu mężczyzn wie jak znaleźć pub...",
         "Co można zdjąć z nagiej sekretarki? Nagiego dyrektora.",
         "Co ma wspólnego chomik i mata? Zapasy :D",
         "Jak się nazywa lans biseksualistów? Bilans.",
         "Co jest czerwone i szkodzi zębów? Cegła.",
         "Dlaczego amerykanie chcą usunąć liczby z lekcji matematyki? Bo są arabskie..."]
